export { default as GameBoard } from './GameBoard.vue'
export { default as GamePiece } from './GamePiece.vue'
export { default as GameRecordBar } from './GameRecordBar.vue'
export { default as GameReplayBar } from './GameReplayBar.vue'
export { default as GameModeBar } from './GameModeBar.vue'
