export { createBoardRenderer, STAR_POINTS } from './BoardRenderer.ts'
export type { BoardRendererOptions, PieceColor } from './BoardRenderer.ts'
export { createCoordMapper, BOARD_SIZE } from './coordMapper.ts'
export type { LogicalPoint, PixelPoint } from './coordMapper.ts'
export { pointerEventToLogical } from './pointerMapper.ts'
